# Generated by Django 5.2.6 on 2025-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('websit', models.URLField(default='')),
                ('date_opened', models.DateField()),
                ('longtitued', models.FloatField()),
                ('lattitude', models.FloatField()),
            ],
        ),
    ]
