# Generated by Django 5.2.6 on 2025-09-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='longtitued',
            new_name='longitued',
        ),
    ]
