# Generated by Django 5.2.6 on 2025-09-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_lattitude_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='longitued',
            new_name='longitude',
        ),
    ]
