# Generated by Django 5.2.6 on 2025-09-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_longitued_restaurant_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='websit',
            new_name='website',
        ),
    ]
